# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c

before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild -workspace Example/RxBinding.xcworkspace -scheme RxBinding-Example -sdk iphonesimulator build CODE_SIGNING_REQUIRED=NO | xcpretty -c
- pod lib lint
